server:
  port: 18083
config:
  config-string: workflow,manager,m-cmp
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: workflow-manager
  # H2 database settings
  datasource:
    url: jdbc:h2:file:./document/test/workflow # Creates the H2 database file under the project root.
    driver-class-name: org.h2.Driver
    username: ${DB_ID:workflow}
    password: ${DB_PW:workflow!23}
  h2:
    console:
      enabled: true # Accessible at http://localhost:18083/h2-console/
      path: /h2-console
      settings:
        web-allow-others: true # Allow remote connections after deployment.
  jpa:
    hibernate:
      ddl-auto: ${DB_INIT_YN:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        hbm2ddl:
          import_files: ""
          connection:
            charSet: UTF-8

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
object:
  object-mapper-pretty-print: true

mc-infra-manager:
  base-url: ${MC_INFRA_MANAGER_URL:http://210.217.178.130:1323/tumblebug}
  username: ${MC_INFRA_MANAGER_USERNAME:default}
  password: ${MC_INFRA_MANAGER_PASSWORD:default}

aes:
  key: fb1755281b0ca6184a0ee644e6477ee7

springdoc:
  paths-to-exclude: [/swagger-resources/**, /v2/**, /v3/**, /error/**, /swagger-ui.html]
#  api-docs:
#    enabled: true
  enable-default-api-docs: true
